name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 检出代码

      - name: Install and deploy
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}  # 从 GitHub Secrets 获取密码
          REMOTE_USER: ${{ secrets.REMOTE_USER }}    # 从 GitHub Secrets 获取用户名
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}    # 从 GitHub Secrets 获取服务器地址
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}    # 从 GitHub Secrets 获取远程路径
        run: |
          sudo apt-get update -y
          sudo apt-get install -y sshpass
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "mkdir -p $REMOTE_PATH"
          sshpass -p $SSH_PASSWORD rsync -avz --delete dist/ $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH
