name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 检出代码

      - name: Install sshpass
        run: |
          sudo apt-get update -y
          sudo apt-get install -y sshpass

      - name: Deploy to Server
        env:
          PASSWORD: ${{ secrets.PASSWORD }}  # 从 GitHub Secrets 获取密码
          USERNAME: ${{ secrets.USERNAME }}    # 从 GitHub Secrets 获取用户名
          HOST: ${{ secrets.HOST }}    # 从 GitHub Secrets 获取服务器地址
          PATH: ${{ secrets.PATH }}    # 从 GitHub Secrets 获取远程路径
        run: |
          sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USER@$HOST "mkdir -p $PATH"
          sshpass -p $PASSWORD rsync -avz --delete dist/ $USER@$HOST:$PATH
